source 'https://rubygems.org'

gem 'jekyll', '~> 4.2.0'
gem 'bundler', '~> 2.0'
gem 'csv', '~> 3.0'
gem 'base64', '~> 0.2.0'
gem 'bigdecimal', '~> 3.1'
gem 'logger', '~> 1.6'
gem 'rexml', '~> 3.3'
gem 'webrick', '~> 1.8'
